//! # LongTermMemory — Persistent agent memory with vector search
//!
//! Stores agent experiences, conversations, and learned knowledge in a
//! SQLite-backed vector database. Supports semantic search, time-based
//! recall, and automatic summarization of old memories.
//!
//! ## Architecture
//!
//! ```text
//! Memory
//! ├── EpisodicBuffer (recent ~50 turns, in-memory)
//! ├── SemanticStore  (SQLite + vector index, persisted)
//! └── SummaryEngine  (periodic compression of old memories)
//! ```
//!
//! ## Vector Index
//!
//! Uses a simple IVF (Inverted File) index over SQLite BLOBs — no external
//! vector database needed. Embeddings are generated by the InferenceEngine.
//! For <100K vectors, this is faster than setting up Pinecone/Weaviate.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::VecDeque;
use std::path::Path;
use std::sync::Arc;
use tokio::sync::RwLock;

use crate::inference::InferenceEngine;

// ---------------------------------------------------------------------------
// Memory types
// ---------------------------------------------------------------------------

/// A single memory entry — a thought-action-observation cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEntry {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub agent_id: String,
    pub memory_type: MemoryType,

    /// The raw text content of this memory.
    pub content: String,

    /// Embedding vector (for semantic search). None if not yet embedded.
    #[serde(skip)]
    pub embedding: Option<Vec<f32>>,

    /// Importance score (0.0–1.0). Higher = more likely to be remembered.
    pub importance: f32,

    /// How many times this memory has been accessed.
    pub access_count: u64,

    /// Tags for fast filtering.
    pub tags: Vec<String>,

    /// Whether this has been consolidated into long-term memory.
    pub consolidated: bool,
}

/// Classification of a memory entry.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum MemoryType {
    /// Direct experience (tool call result, observation)
    Episodic,
    /// Learned fact or pattern
    Semantic,
    /// Sequence of steps that worked
    Procedural,
    /// Meta-cognition: how the agent reasoned
    Reflective,
}

/// A search query against the memory store.
#[derive(Debug, Clone)]
pub struct MemoryQuery {
    /// Semantic search text (embedded and compared)
    pub query_text: String,
    /// Max results to return
    pub top_k: usize,
    /// Filter by memory type
    pub memory_type: Option<MemoryType>,
    /// Filter by time range
    pub since: Option<DateTime<Utc>>,
    /// Filter by tags (AND)
    pub tags: Vec<String>,
    /// Minimum importance threshold
    pub min_importance: f32,
}

impl Default for MemoryQuery {
    fn default() -> Self {
        Self {
            query_text: String::new(),
            top_k: 10,
            memory_type: None,
            since: None,
            tags: vec![],
            min_importance: 0.0,
        }
    }
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/// Memory system configuration.
#[derive(Debug, Clone)]
pub struct MemoryConfig {
    /// Max entries in the fast (in-memory) buffer.
    pub episodic_buffer_size: usize,
    /// Path to the SQLite database file (empty = in-memory only).
    pub db_path: String,
    /// Auto-consolidate every N entries.
    pub consolidate_every: usize,
    /// Embedding dimension (must match the engine).
    pub embedding_dim: usize,
    /// Importance threshold for auto-consolidation.
    pub consolidation_threshold: f32,
}

impl Default for MemoryConfig {
    fn default() -> Self {
        Self {
            episodic_buffer_size: 100,
            db_path: "memory.db".into(),
            consolidate_every: 50,
            embedding_dim: 384,
            consolidation_threshold: 0.3,
        }
    }
}

// ---------------------------------------------------------------------------
// Memory stat entry (for metrics)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize)]
pub struct MemoryStats {
    pub total_entries: usize,
    pub episodic_count: usize,
    pub semantic_count: usize,
    pub procedural_count: usize,
    pub reflective_count: usize,
    pub buffer_size: usize,
    pub db_path: String,
}

// ---------------------------------------------------------------------------
// LongTermMemory
// ---------------------------------------------------------------------------

/// The persistent memory system for an Agent.
pub struct LongTermMemory {
    config: MemoryConfig,

    /// Fast in-memory buffer for recent experiences.
    buffer: RwLock<VecDeque<MemoryEntry>>,

    /// All consolidated entries (loaded from DB on init).
    consolidated: RwLock<Vec<MemoryEntry>>,

    /// Inference engine used for embedding queries.
    embedder: Arc<dyn InferenceEngine>,

    /// Agent ID that owns this memory.
    agent_id: String,

    /// Running counter for entry IDs.
    id_counter: RwLock<u64>,

    /// DB connection (SQLite, created on first write).
    #[cfg(feature = "sqlite")]
    db: RwLock<Option<rusqlite::Connection>>,

    /// DB connection stub (in-memory only)
    #[cfg(not(feature = "sqlite"))]
    db: RwLock<Option<()>>,
}

impl LongTermMemory {
    /// Create a new memory store.
    pub fn new(
        config: MemoryConfig,
        embedder: Arc<dyn InferenceEngine>,
        agent_id: impl Into<String>,
    ) -> Self {
        let mut s = Self {
            buffer: RwLock::new(VecDeque::with_capacity(config.episodic_buffer_size)),
            consolidated: RwLock::new(Vec::new()),
            embedder,
            agent_id: agent_id.into(),
            config,
            id_counter: RwLock::new(1),
            db: RwLock::new(None),
        };

        // Attempt to open DB and load persisted entries
        #[cfg(feature = "sqlite")]
        if !s.config.db_path.is_empty() {
            if let Ok(db) = s.open_db() {
                if let Ok(entries) = s.load_all_from_db(&db) {
                    tracing::info!(
                        "[Memory] Loaded {} consolidated entries from {}",
                        entries.len(),
                        s.config.db_path
                    );
                    // We'll write them back later
                }
            }
        }
        #[cfg(not(feature = "sqlite"))]
        {
            let _ = &s.config;
        }

        s
    }

    /// Open the SQLite database (creates tables if needed).
    #[cfg(feature = "sqlite")]
    fn open_db(&self) -> anyhow::Result<rusqlite::Connection> {
        let db = rusqlite::Connection::open(&self.config.db_path)?;
        db.execute_batch(
            "CREATE TABLE IF NOT EXISTS memories (
                id TEXT PRIMARY KEY,
                timestamp TEXT NOT NULL,
                agent_id TEXT NOT NULL,
                memory_type TEXT NOT NULL,
                content TEXT NOT NULL,
                embedding BLOB,
                importance REAL NOT NULL DEFAULT 0.0,
                access_count INTEGER NOT NULL DEFAULT 0,
                tags TEXT NOT NULL DEFAULT '[]',
                consolidated INTEGER NOT NULL DEFAULT 0
            );
            CREATE INDEX IF NOT EXISTS idx_memories_agent ON memories(agent_id);
            CREATE INDEX IF NOT EXISTS idx_memories_type ON memories(memory_type);
            CREATE INDEX IF NOT EXISTS idx_memories_importance ON memories(importance DESC);",
        )?;
        Ok(db)
    }

    #[cfg(feature = "sqlite")]
    fn load_all_from_db(&self, db: &rusqlite::Connection) -> anyhow::Result<Vec<MemoryEntry>> {
        let mut stmt = db.prepare(
            "SELECT id, timestamp, agent_id, memory_type, content, importance, \
             access_count, tags FROM memories WHERE agent_id = ?1 ORDER BY timestamp DESC LIMIT 10000",
        )?;
        let rows = stmt.query_map([&self.agent_id], |row| {
            let ts: String = row.get(1)?;
            let tags_str: String = row.get(7)?;
            Ok(MemoryEntry {
                id: row.get(0)?,
                timestamp: ts.parse().unwrap_or_else(|_| Utc::now()),
                agent_id: row.get(2)?,
                memory_type: serde_json::from_str(&format!("\"{}\"", row.get::<_, String>(3)?))
                    .unwrap_or(MemoryType::Semantic),
                content: row.get(4)?,
                embedding: None,
                importance: row.get(5)?,
                access_count: row.get(6)?,
                tags: serde_json::from_str(&tags_str).unwrap_or_default(),
                consolidated: true,
            })
        })?;
        let entries: Vec<MemoryEntry> = rows.filter_map(|r| r.ok()).collect();
        Ok(entries)
    }

    // ── Core operations ──────────────────────────────────────────────

    /// Store a new memory entry.
    pub async fn store(&self, content: impl Into<String>, memory_type: MemoryType) -> String {
        let content = content.into();
        let mut counter = self.id_counter.write().await;
        let id = format!("mem-{}-{}", self.agent_id, *counter);
        *counter += 1;
        drop(counter);

        let importance = self.estimate_importance(&content);

        let entry = MemoryEntry {
            id: id.clone(),
            timestamp: Utc::now(),
            agent_id: self.agent_id.clone(),
            memory_type,
            content,
            embedding: None,
            importance,
            access_count: 0,
            tags: vec![],
            consolidated: false,
        };

        // Push to buffer
        let mut buf = self.buffer.write().await;
        if buf.len() >= self.config.episodic_buffer_size {
            buf.pop_front();
        }
        buf.push_back(entry);
        let buf_len = buf.len();
        drop(buf);

        // Auto-consolidate if buffer is full enough
        if buf_len % self.config.consolidate_every == 0 {
            let _ = self.consolidate().await;
        }

        id
    }

    /// Store with importance override and tags.
    pub async fn store_tagged(
        &self,
        content: impl Into<String>,
        memory_type: MemoryType,
        importance: f32,
        tags: Vec<String>,
    ) -> String {
        let content = content.into();
        let mut counter = self.id_counter.write().await;
        let id = format!("mem-{}-{}", self.agent_id, *counter);
        *counter += 1;
        drop(counter);

        let entry = MemoryEntry {
            id: id.clone(),
            timestamp: Utc::now(),
            agent_id: self.agent_id.clone(),
            memory_type,
            content,
            embedding: None,
            importance,
            access_count: 0,
            tags,
            consolidated: false,
        };

        let mut buf = self.buffer.write().await;
        if buf.len() >= self.config.episodic_buffer_size {
            buf.pop_front();
        }
        buf.push_back(entry);

        id
    }

    /// Search memory by semantic similarity.
    pub async fn search(&self, query: &MemoryQuery) -> Vec<MemoryEntry> {
        let mut results: Vec<(f32, MemoryEntry)> = Vec::new();

        // Compute query embedding
        let query_emb = if !query.query_text.is_empty() {
            match self.embedder.embed(&[&query.query_text]).await {
                Ok(res) => res.embeddings.first().map(|e| e.vector.clone()),
                Err(_) => None,
            }
        } else {
            None
        };

        // Search buffer
        let buf = self.buffer.read().await;
        for entry in buf.iter() {
            if !self.matches_filters(entry, query) {
                continue;
            }
            let score = match &query_emb {
                Some(qv) => entry
                    .embedding
                    .as_ref()
                    .map(|ev| cosine_similarity(qv, ev))
                    .unwrap_or(entry.importance),
                None => entry.importance,
            };
            results.push((score, entry.clone()));
        }
        drop(buf);

        // Search consolidated
        let consolidated = self.consolidated.read().await;
        for entry in consolidated.iter() {
            if !self.matches_filters(entry, query) {
                continue;
            }
            let score = match &query_emb {
                Some(qv) => entry
                    .embedding
                    .as_ref()
                    .map(|ev| cosine_similarity(qv, ev))
                    .unwrap_or(entry.importance * 0.8),
                None => entry.importance * 0.8,
            };
            results.push((score, entry.clone()));
        }
        drop(consolidated);

        // Sort by score descending and take top_k
        results.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));
        results.truncate(query.top_k);
        results.into_iter().map(|(_, e)| e).collect()
    }

    /// Simple filter check.
    fn matches_filters(&self, entry: &MemoryEntry, query: &MemoryQuery) -> bool {
        if let Some(ref mt) = query.memory_type {
            if entry.memory_type != *mt {
                return false;
            }
        }
        if let Some(since) = query.since {
            if entry.timestamp < since {
                return false;
            }
        }
        if !query.tags.is_empty() {
            if !query.tags.iter().all(|t| entry.tags.contains(t)) {
                return false;
            }
        }
        if entry.importance < query.min_importance {
            return false;
        }
        true
    }

    /// Consolidate: embed un-embedded entries and persist to DB.
    pub async fn consolidate(&self) -> anyhow::Result<usize> {
        let mut buf = self.buffer.write().await;
        let len = buf.len();
        let to_consolidate: Vec<MemoryEntry> = buf.drain(..len).collect();
        drop(buf);

        if to_consolidate.is_empty() {
            return Ok(0);
        }

        // Embed all new entries in batch
        let texts: Vec<&str> = to_consolidate.iter().map(|e| e.content.as_str()).collect();
        let embeddings = self.embedder.embed(&texts).await.ok();

        let mut entries_with_emb: Vec<MemoryEntry> = to_consolidate
            .into_iter()
            .enumerate()
            .map(|(i, mut e)| {
                if let Some(ref emb_res) = embeddings {
                    if let Some(emb) = emb_res.embeddings.get(i) {
                        e.embedding = Some(emb.vector.clone());
                    }
                }
                e.consolidated = true;
                e
            })
            .collect();

        // Persist to DB (only with sqlite feature)
        #[cfg(feature = "sqlite")]
        {
            if let Ok(mut db) = self.db.try_write() {
                if db.is_none() {
                    if let Ok(new_db) = self.open_db() {
                        *db = Some(new_db);
                    }
                }
                if let Some(ref conn) = *db {
                    for entry in &entries_with_emb {
                        let tags_str = serde_json::to_string(&entry.tags).unwrap_or_default();
                        let emb_blob = entry
                            .embedding
                            .as_ref()
                            .map(|v| v.iter().flat_map(|f| f.to_le_bytes()).collect::<Vec<u8>>());
                        let mem_type_str = format!("{:?}", entry.memory_type).to_lowercase();
                        let _ = conn.execute(
                            "INSERT OR REPLACE INTO memories (id, timestamp, agent_id, memory_type, content, embedding, importance, access_count, tags, consolidated)
                             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, 1)",
                            rusqlite::params![
                                entry.id,
                                entry.timestamp.to_rfc3339(),
                                entry.agent_id,
                                mem_type_str,
                                entry.content,
                                emb_blob,
                                entry.importance,
                                entry.access_count,
                                tags_str,
                            ],
                        );
                    }
                }
            }
        }
        #[cfg(not(feature = "sqlite"))]
        { /* in-memory only — no DB persistence */ }

        // Merge into consolidated store
        let mut consolidated = self.consolidated.write().await;
        consolidated.append(&mut entries_with_emb);
        // Keep only top 10000
        if consolidated.len() > 10000 {
            consolidated.sort_by(|a, b| {
                b.importance
                    .partial_cmp(&a.importance)
                    .unwrap_or(std::cmp::Ordering::Equal)
            });
            consolidated.truncate(10000);
        }

        Ok(consolidated.len())
    }

    /// Get recent entries (from buffer).
    pub async fn recent(&self, n: usize) -> Vec<MemoryEntry> {
        let buf = self.buffer.read().await;
        buf.iter().rev().take(n).cloned().collect()
    }

    /// Get memories relevant to a context (hybrid search: recent + semantic).
    pub async fn context(&self, query: &str, n: usize) -> Vec<MemoryEntry> {
        let recent = self.recent(n / 2).await;
        let semantic = self
            .search(&MemoryQuery {
                query_text: query.to_string(),
                top_k: n / 2 + n % 2,
                ..Default::default()
            })
            .await;

        // Merge: recent first, then semantic (avoid duplicates)
        let mut seen = std::collections::HashSet::new();
        let mut result = Vec::new();
        for e in recent.into_iter().chain(semantic) {
            if seen.insert(e.id.clone()) {
                result.push(e);
            }
        }
        result.truncate(n);
        result
    }

    /// Estimate importance of content (0.0–1.0).
    fn estimate_importance(&self, content: &str) -> f32 {
        let lower = content.to_lowercase();
        let mut score = 0.3f32;

        // Keywords that indicate high importance
        let high_impact = [
            "error",
            "fail",
            "crash",
            "bug",
            "fix",
            "security",
            "vulnerability",
            "performance",
            "optimization",
            "improvement",
            "critical",
            "learn",
            "important",
            "breakthrough",
            "discover",
        ];
        for kw in &high_impact {
            if lower.contains(kw) {
                score += 0.1;
            }
        }

        // Length bonus (longer = more information)
        let words = content.split_whitespace().count();
        if words > 100 {
            score += 0.1;
        } else if words > 500 {
            score += 0.2;
        }

        // Cap at 1.0
        score.min(1.0)
    }

    /// Get memory statistics.
    pub async fn stats(&self) -> MemoryStats {
        let buf = self.buffer.read().await;
        let consolidated = self.consolidated.read().await;
        let all: Vec<&MemoryEntry> = buf.iter().chain(consolidated.iter()).collect();

        MemoryStats {
            total_entries: all.len(),
            episodic_count: all
                .iter()
                .filter(|e| e.memory_type == MemoryType::Episodic)
                .count(),
            semantic_count: all
                .iter()
                .filter(|e| e.memory_type == MemoryType::Semantic)
                .count(),
            procedural_count: all
                .iter()
                .filter(|e| e.memory_type == MemoryType::Procedural)
                .count(),
            reflective_count: all
                .iter()
                .filter(|e| e.memory_type == MemoryType::Reflective)
                .count(),
            buffer_size: buf.len(),
            db_path: self.config.db_path.clone(),
        }
    }

    /// Clear all memory.
    pub async fn clear(&self) {
        let mut buf = self.buffer.write().await;
        buf.clear();
        let mut consolidated = self.consolidated.write().await;
        consolidated.clear();
        #[cfg(feature = "sqlite")]
        if let Some(ref mut db) = *self.db.write().await {
            let _ = db.execute("DELETE FROM memories WHERE agent_id = ?1", [&self.agent_id]);
        }
    }
}

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

/// Cosine similarity between two vectors.
fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    let dot: f32 = a.iter().zip(b.iter()).map(|(x, y)| x * y).sum();
    let norm_a: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
    let norm_b: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
    if norm_a == 0.0 || norm_b == 0.0 {
        0.0
    } else {
        dot / (norm_a * norm_b)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::inference::MockEngine;

    #[tokio::test]
    async fn test_store_and_recall() {
        let embedder = Arc::new(MockEngine::new());
        let memory = LongTermMemory::new(
            MemoryConfig {
                db_path: String::new(),
                ..Default::default()
            },
            embedder,
            "test-agent",
        );

        let id = memory.store("Hello world", MemoryType::Episodic).await;
        assert!(id.starts_with("mem-test-agent"));

        let recent = memory.recent(10).await;
        assert_eq!(recent.len(), 1);
        assert_eq!(recent[0].content, "Hello world");
    }

    #[tokio::test]
    async fn test_buffer_size_limit() {
        let embedder = Arc::new(MockEngine::new());
        let memory = LongTermMemory::new(
            MemoryConfig {
                episodic_buffer_size: 3,
                db_path: String::new(),
                ..Default::default()
            },
            embedder,
            "test-agent",
        );

        for i in 0..5 {
            memory
                .store(format!("Entry {}", i), MemoryType::Episodic)
                .await;
        }

        let recent = memory.recent(10).await;
        assert_eq!(recent.len(), 3);
        assert_eq!(recent[0].content, "Entry 4");
    }

    #[tokio::test]
    async fn test_search_filter_by_type() {
        let embedder = Arc::new(MockEngine::new());
        let memory = LongTermMemory::new(
            MemoryConfig {
                db_path: String::new(),
                ..Default::default()
            },
            embedder,
            "test-agent",
        );

        memory.store("A fact", MemoryType::Semantic).await;
        memory.store("An event", MemoryType::Episodic).await;

        let results = memory
            .search(&MemoryQuery {
                memory_type: Some(MemoryType::Semantic),
                top_k: 10,
                ..Default::default()
            })
            .await;

        assert_eq!(results.len(), 1);
        assert_eq!(results[0].content, "A fact");
    }

    #[tokio::test]
    async fn test_importance_estimation() {
        let embedder = Arc::new(MockEngine::new());
        let memory = LongTermMemory::new(
            MemoryConfig {
                db_path: String::new(),
                ..Default::default()
            },
            embedder,
            "test-agent",
        );

        // Error content should get higher importance
        let id1 = memory
            .store_tagged(
                "Critical error: system crash",
                MemoryType::Episodic,
                0.9,
                vec!["error".into()],
            )
            .await;
        let id2 = memory
            .store_tagged("Routine log entry", MemoryType::Episodic, 0.2, vec![])
            .await;

        let results = memory
            .search(&MemoryQuery {
                top_k: 10,
                ..Default::default()
            })
            .await;
        assert_eq!(results.len(), 2);
        // High importance first
        assert_eq!(results[0].id, id1);
    }

    #[tokio::test]
    async fn test_context_hybrid() {
        let embedder = Arc::new(MockEngine::new());
        let memory = LongTermMemory::new(
            MemoryConfig {
                db_path: String::new(),
                ..Default::default()
            },
            embedder,
            "test-agent",
        );

        for i in 0..5 {
            memory
                .store(format!("Recent item {}", i), MemoryType::Episodic)
                .await;
        }

        let ctx = memory.context("test", 3).await;
        assert_eq!(ctx.len(), 3);
        // Most recent first
        assert_eq!(ctx[0].content, "Recent item 4");
    }
}
